### ISSUE TITLE
Send Basic Auth Request

### ISSUE THREAD

**Issue by jeffbrown** [jeffbrown/five15#13]
We need to modify the front end to send a Basic Auth request to the server.

**Comment by jeffbrown** [comment]
Can @craigburke or @VoltiSubito put this in place?

**Comment by jeffbrown** [comment]
Any update on this @craigburke?

**Comment by craigburke** [comment]
Yeah, I'll clean up what I have and push either today or tomorrow.

**Comment by craigburke** [comment]
Ok, committed. This is making a POST request to `/auth/login` and expecting back a JSON response similar to this:
```
{id: 'craig', roles: ['ADMIN']}
```

**Comment by jeffbrown** [comment]
Excellent.  I will get started on #14.
