### ISSUE TITLE
Javascript Closure AP Module

### ISSUE THREAD

**Issue by craigburke** [jeffbrown/five15#4]
I need to not see anonymous JS closure in every file or I'll throw up.

**Comment by craigburke** [comment]
Newly created module:
https://github.com/craigburke/js-closure-wrap-asset-pipeline

I'll add it to the project as soon as I can publish it to jCenter.

**Comment by craigburke** [comment]
I still need to add inclusions/exclusions config options to this module so that it isn't applied to all js files in the project.

**Comment by craigburke** [comment]
@VoltiSubito here's the commit for this:
https://github.com/jeffbrown/five15/commit/66025449ef57e423591f237d2a8b9ef9921f7034

I think there's a lot less noise in the JS files now. Let me know if looks good to you.

**Comment by VoltiSubito** [comment]
@craigburke Nice!  I like it.
