### ISSUE TITLE
Validate remainder of AnguarJS code against style guide

### ISSUE THREAD

**Issue by VoltiSubito** [jeffbrown/five15#8]
I'm assuming this one:

https://github.com/johnpapa/angular-styleguide

**Comment by craigburke** [comment]
Todd Motto's is also really good but there's a ton of overlap between the two:
https://github.com/toddmotto/angularjs-styleguide

**Comment by craigburke** [comment]
BTW, please tell me if these suggestions are more annoying than helpful and I'll stop :smile:

**Comment by VoltiSubito** [comment]
I've not seen Todd Motto's.  I'm looking forward to going through it.  There are a few things I dislike about the John Papa guide but I agree that we should stick to a community standard for this project.

I always appreciate suggestions.  :)

**Comment by VoltiSubito** [comment]
I really like the Controller.resolve idea.  Wish I'd thought of that.

**Comment by craigburke** [comment]
Wow, I missed that one. Yeah, that's awesome. I really like that Controller.resolve idea a lot!

**Comment by craigburke** [comment]
I imagine I'm going to be stealing a lot of idea from this project in my other Angular projects :smiley:
